/*
 * generated by Xtext 2.21.0
 */
package de.fhdo.sep.ml_example.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class StructureDslIdeModule extends AbstractStructureDslIdeModule {
}
